### ISSUE TITLE
cheerio.load improperly escaping characters

### ISSUE THREAD

**Issue by nsimonson** [jfrolich/elixir-smoothie#5]
There's an issue with cheerio encoding apostrophes incorrectly. https://github.com/cheeriojs/cheerio/issues/319 

If I try to say use a string within my elixir variable `<img src="<%= static_url('/images/img.png') %>">` This gets improperly escaped as `<img src="<%= static_url(&amp;apos;/images/img.png&amp;apos;) %>">`. Wrapping this line with the Inky `<raw>` tag yields me `<img src="<%= static_url(&apos;/images/img.png&apos;) %>">`. This is closer, but doesn't deal with cheerio escaping the initial single quote. This gets cleared up by setting the cheerioOpts `decodeEntities: false`.

```
let $ = cheerio.load(escapeEex(template), {xmlMode: true, decodeEntities: false});
```

I'm not able to check if this has any side effects because `__tests__` seems to be missing the template directories.

**Comment by jfrolich** [comment]
Thanks, travelling now, but will investigate coming week!

**Comment by nsimonson** [comment]
I suppose this ends up being kind of moot since I've worked around the issue. I ended up building these links and passing the string in as a normal variable. 

Since images in emails always need to have absolute paths, Ideally I could do something like `<%= MyApp.Router.Helpers.static_url(MyApp.Endpoint, ~s(/images/img.png)) %>`. However everything within `<%= ... %>` gets pulled out into @variables and I get an unused variable warning. It's less of a bug and more of a flaw in how Smoothie deals with variables.

**Comment by jfrolich** [comment]
FYI: this should be fixed in the current version!

**Comment by jfrolich** [comment]
Would be great if you could verify this in your use case

**Comment by nsimonson** [comment]
Looks like the issue with escaping characters is resolved. Thanks!
